### ISSUE TITLE
add key management to rainspub

### ISSUE THREAD

**Issue by britram** [netsec-ethz/rains#104]
rainspub (or an affiliated command) needs to allow a user to create a new keypair, and to manage that keypair.

Remove or relocate keys.PrivateKey struct once we use the key manager in rainsPub

**Comment by britram** [comment]
partially addressed by #151

**Comment by fehlmach** [comment]
How to obtain the passwords to decrypt the private keys. Store them in conf file to be able to publish without user interaction?
