### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by abdul-manaan** [netsec-ethz/rains#225]
I am tring to build RAINS, but it has some problem in dependencies installation:

When we do `go get ./...` , following error appears:

# github.com/scionproto/scion/go/proto
../../scionproto/scion/go/proto/sign.go:29:12: undefined: SignType
# github.com/scionproto/scion/go/lib/scrypto/trc
../../scionproto/scion/go/lib/scrypto/trc/trc.go:163:32: too many arguments in call to lz4.UncompressBlock
	have (common.RawBytes, []byte, number)
	want ([]byte, []byte)
../../scionproto/scion/go/lib/scrypto/trc/trc.go:371:45: cannot use 0 (type int) as type []int in argument to lz4.CompressBlock

I am using Ubuntu 16.04, Go version 1.9 and 1.12 both have same problem,

**Comment by Oncilla** [comment]
From offline discussion:

Bazel handles the dependency management. There is no need for running `go get` on the scionproto/scion repository.
Please follow the readme (https://github.com/scionproto/scion/blob/master/README.md) up until step 5 at least.
