### ISSUE TITLE
Replace IP4 and IP6 object value with net.IPAddr (instead of string)

### ISSUE THREAD

**Issue by fehlmach** [netsec-ethz/rains#95]

**Comment by rayhaanj** [comment]
Relevant in CBOR side:
https://github.com/netsec-ethz/rains/blob/master/internal/pkg/object/object.go#L36-L41
https://github.com/netsec-ethz/rains/blob/master/internal/pkg/object/object.go#L167-L174

**Comment by chaehni** [comment]
closed by https://github.com/netsec-ethz/rains/pull/224
