### ISSUE TITLE
create a rainsd command

### ISSUE THREAD

**Issue by britram** [netsec-ethz/rains#96]
Actually running a RAINS server requires someone to write Go code that instantiates and configures a RAINS server from objects defined in an internal package. This is not, how shall I put it, compatible with common operational practice.

To be reasonably deployable (e.g., in SCIONlab), we'll need a sciond that is designed to be run from various system management approaches (e.g. *shudder* `systemd`), taking its configuration from configuration files and command line arguments.

**Comment by britram** [comment]
This appears to be related to #87 and #36.

**Comment by rayhaanj** [comment]
I believe this is what this file implements:
https://github.com/netsec-ethz/rains/blob/master/examples/server/main.go

It probably needs some cleanup but it is possible to just run that binary with a config file and the appropriate keys in the pwd. At least that is how the integration tests worked.

Probably doesn't help that it's in a folder called examples though.

**Comment by britram** [comment]
>> which allows to overwrite settings in a given config file

Huh? not clear why rainsd needs to edit its configuration file?

**Comment by fehlmach** [comment]
Maybe the formulation was not specific enough: There are several ways to start up a server. Two of them would be:
1) Have a small program which takes the path to a config file and starts the server
2) Have a cmd line tool where you can specify all the server configs and those that are not specified have some default value or are loaded from a given specification.

**Comment by britram** [comment]
ah. override, not overwrite. sorry, got it :)
